### ISSUE TITLE
Copy from HDFS not working

### ISSUE THREAD

**Issue by mayur7789** [Esri/gis-tools-for-hadoop#22]
Here is the error details
![model](https://cloud.githubusercontent.com/assets/10476589/5691945/f8da8b2c-9904-11e4-80b9-ffeb888c401e.PNG)

I have Windows 7 as Host machine and Cloudera VM (Linux) as guest machine. Arcmap is installed on Host machine please find the screen shot below while accessing.
![clouderavmnamenode](https://cloud.githubusercontent.com/assets/10476589/5691953/4634dc6a-9905-11e4-86f6-d4978fa4d81e.PNG)
http://quickstart.cloudera:50070/dfshealth.html#tab-overview (192.168.126.128:50070/) through browser on the same machine as ArcMap.

Also tried solving the problem with the help of "Copy to HDFS not working #16" But still I am facing the same problem.
![clouderavm ss](https://cloud.githubusercontent.com/assets/10476589/5691958/83d817b2-9905-11e4-858a-154970d304b3.PNG)

Please point me to right direction.

**Comment by climbage** [comment]
Can you make the tool work by using the IP address of the namenode rather than the hostname?

**Comment by mayur7789** [comment]
@climbage : No I tired using the tool with IP address but couldn't make it work, any other solution.

**Comment by randallwhitman** [comment]
The third image in the issue description of 2015/01/10 does not appear to be the "same problem" as the first image - it is very different.  The third image shows a web browser [Firefox] dialog asking which application should be used to open the CSV file.  In fact, such a web browser dialog indicates a *successful* download of the requested file.  This may not provide entirely relevant information, as the screenshot appears to be a web browser running in the guest OS in the VM, and no screen shot is provided of a browser on the host OS trying to access the file through that URL.

**Comment by GISDev01** [comment]
@mayur7789 If you did not figure this out yet, it looks like you are using "quickstart" as an input to the GP tool from your first screenshot. It is likely that your host machine has no idea where this location of "quickstart" is located unless you actually put quick in your Windows HOSTS file. As Randall mentions, you should try accessing the same URL in your 3rd screenshot from within a web browser on your host machine instead of from within the Cloudera VM. This test it to make sure webhdfs is accessible from the host machine (the same one running the GP tool from within ArcMap) to the Cloudera VM.

If the IP URL that is shown in your third screenshot works in your host machine web browser, then trying switching your input param. within your GP tool in ArcMap from "quickstart" to just the IPv4 address which you used in the URL webhdfs test.

**Comment by JamesMilnerUK** [comment]
I am having the same issue with the out the box VM provided via https://github.com/Esri/gis-tools-for-hadoop/wiki/GIS-Tools-for-Hadoop-for-Beginners . I have followed all the instructions however I hit the same error whilst trying to run the Copy to HDFS script. I have a feeling that as per @GISDev01 the host machine has no way of desiphering what sandbox or sandbox.hortonworks.com actually is, but i'm not sure how to make that happen. If you have either @mayur7789 , @randallwhitman or @climbage have any ideas that would be greatly appreciated as I'm supposed to be demoing it soon.

![image](https://cloud.githubusercontent.com/assets/8822075/7051371/d3274086-de1f-11e4-9056-819bed35a0d8.png)
 

![image](https://cloud.githubusercontent.com/assets/8822075/7051395/f71da7be-de1f-11e4-9ead-766daf778fde.png)

**Comment by climbage** [comment]
@JamesMBallard Can you change `sandbox` to `localhost`?

**Comment by JamesMBallard** [comment]
Wrong James...

**Comment by JamesMilnerUK** [comment]
@climbage thanks! That worked (woops, what a simple mistake). However now I'm faced with a new error... "Unexpected error : No JSON object could be decoded". Perhaps something funky going on with the actual created file?

![image](https://cloud.githubusercontent.com/assets/8822075/7051641/a8fdc62a-de21-11e4-8ff8-a2987dbec7de.png)

**Comment by climbage** [comment]
@JamesMilnerUK Could be.  Can you browse to the file in HDFS?  http://localhost:50070

**Comment by JamesMilnerUK** [comment]
@climbage for sure; this is what I see.
![image](https://cloud.githubusercontent.com/assets/8822075/7051760/7897d650-de22-11e4-8b48-5720c3fbcb0d.png)

**Comment by climbage** [comment]
@JamesMilnerUK is there a link on that page to browse the file system?

**Comment by JamesMilnerUK** [comment]
@climbage yeah, so I can browse to the file, however when I try and open the agg_samp I get file not found
![image](https://cloud.githubusercontent.com/assets/8822075/7051886/1e2baa06-de23-11e4-9ccb-4f9005403568.png)
![image](https://cloud.githubusercontent.com/assets/8822075/7051916/49678762-de23-11e4-846c-02484f535acf.png)

**Comment by climbage** [comment]
Hmm, and you created dataset through the hive sample?

**Comment by JamesMilnerUK** [comment]
@climbage Yeah, I'm following the workflow as described on https://github.com/Esri/gis-tools-for-hadoop/wiki/Getting-the-results-of-a-Hive-query-into-ArcGIS . Everything appears to run correctly: 
![image](https://cloud.githubusercontent.com/assets/8822075/7052138/8e2c60f6-de24-11e4-8159-4d1225af74a9.png)

But I get the JSON error now whilst running the Copy from HDFS tool

**Comment by climbage** [comment]
How about `select count(*) from agg_samp`?

**Comment by JamesMilnerUK** [comment]
@climbage if I replace event_date with earthquake_date it comes back with "OK 12948"

**Comment by climbage** [comment]
When are you replacing it?

**Comment by JamesMilnerUK** [comment]
Replacing event_date (as described in tutorial: https://github.com/Esri/gis-tools-for-hadoop/wiki/Getting-the-results-of-a-Hive-query-into-ArcGIS) with earthsquake_date because otherwise it fails.

CREATE TABLE IF NOT EXISTS earthquakes (earthquake_date STRING, latitude DOUBLE, longitude DOUBLE, magnitude DOUBLE)
ROW FORMAT DELIMITED FIELDS TERMINATED BY ',';
LOAD DATA LOCAL INPATH './earthquakes.csv' OVERWRITE INTO TABLE earthquakes;

CREATE TABLE earthquakes_new(earthquake_date STRING, latitude DOUBLE, longitude DOUBLE, magnitude DOUBLE);
INSERT OVERWRITE TABLE earthquakes_new
SELECT earthquake_date, latitude, longitude, magnitude
FROM earthquakes
WHERE latitude is not null;

Thank you for your help by the way.

**Comment by climbage** [comment]
Interesting.  So what if you re-run the GP tool now?

**Comment by JamesMilnerUK** [comment]
The hive commands pass per screenshot provided above. The GP tool gives: Unexpected error : No JSON object could be decoded

Interestingly if I copy the JSON to my desktop and run the second GP task (JSON to Feature Layer) I get this:

![image](https://cloud.githubusercontent.com/assets/8822075/7052836/f76923ca-de28-11e4-8b35-080add27a4b6.png)


I'm not sure if this is how it's supposed to look as no example is provided, but I'm assuming that it is correct (feature table looks OK; visualises OK).

**Comment by climbage** [comment]
Well, that is how it's supposed to look so you're at least getting the right results.

Actually, I think I might know why the copy from HDFS too is not working.  Instead of,

`apps/hive/warehouse/...`

use 

`/apps/hive/warehouse/...`

If you don't root the path it will assume it's relative to your home directory `/users/[username]`

**Comment by JamesMilnerUK** [comment]
Thanks for the suggestion. I have attempted it and unforunately still getting the same error: (Unexpected error : [Errno 11004] getaddrinfo failed).

Also, just out of interest what is this query doing? Aggregating the number of earthquakes in a year into square polygons?

**Comment by climbage** [comment]
Can you post the traceback for the error this time?

**Comment by JamesMilnerUK** [comment]
Executing: CopyFromHDFS localhost 50070 root     apps/hive/warehouse/agg_samp C:\Users\jmilner\Desktop\earthquakes3.json
Start Time: Wed Apr 08 20:35:45 2015
Running script CopyFromHDFS...
Unexpected error : No JSON object could be decoded
Traceback (most recent call last):
  File "<string>", line 265, in execute
  File "C:\Users\jmilner\Documents\Developer Evangelist\GeoDev Meetups\GeoDev2\geoprocessing-tools-for-hadoop\webhdfs\webhdfs.py", line 181, in getFileStatus
    data_dict = json.loads(response.read())
  File "C:\Python27\Lib\json\__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "C:\Python27\Lib\json\decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Python27\Lib\json\decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

**Comment by climbage** [comment]
It still looks like you don't have a `/` at the beginning of your path

**Comment by JamesMilnerUK** [comment]
@climbage if I put a / I get the old error:

    Unexpected error : [Errno 11004] getaddrinfo failed
    Traceback (most recent call last):
    File "<string>", line 277, in execute
    File "C:\Users\jmilner\Documents\Developer Evangelist\GeoDev    Meetups\GeoDev2\geoprocessing-tools-for-hadoop\webhdfs\webhdfs.py", line 152, in    copyFromHDFS
    fileDownloadClient.request('GET', redirect_path, headers={})
    File "C:\Python27\Lib\httplib.py", line 995, in request
    self._send_request(method, url, body, headers)
    File "C:\Python27\Lib\httplib.py", line 1029, in _send_request
    self.endheaders(body)
    File "C:\Python27\Lib\httplib.py", line 991, in endheaders
    self._send_output(message_body)
    File "C:\Python27\Lib\httplib.py", line 844, in _send_output
    self.send(msg)
    File "C:\Python27\Lib\httplib.py", line 806, in send
    self.connect()
    File "C:\Python27\Lib\httplib.py", line 787, in connect
    self.timeout, self.source_address)
    File "C:\Python27\Lib\socket.py", line 553, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
    gaierror: [Errno 11004] getaddrinfo failed

**Comment by climbage** [comment]
That's what I'm looking for.  This is *slightly* different in that now you're getting an error during redirection to a datanode.  

Try this in the browser and see what you get.

`http://localhost:50070/webhdfs/v1/apps/hive/warehouse/agg_samp/000000_0?op=OPEN`

**Comment by JamesMilnerUK** [comment]
Thanks again. Unforunately I get "This web page is not available" . I'm redirected to:

     http://sandbox.hortonworks.com:50075/webhdfs/v1/apps/hive/warehouse/agg_samp/000000_0

**Comment by GISDev01** [comment]
@JamesMilnerUK Is sandbox.hortonworks.com in your Windows hosts file?

**Comment by climbage** [comment]
Now we're getting somewhere.  @GISDev01 has the solution.  @smambrose can we put this in the tutorials?

**Comment by JamesMilnerUK** [comment]
I added 
    sandbox.hortonworks.com localhost
to my host file but that didn't work. Am I doing something wrong?

**Comment by climbage** [comment]
I believe it should be...

    127.0.0.1     sandbox.hortonworks.com

**Comment by GISDev01** [comment]
The IP in your Windows OS hosts file is going to be the IP of your Hortonworks VM. The IP of the Hortonworks VM is highly dependent on your VM settings.

**Comment by JamesMilnerUK** [comment]
Awesome! Got it working :)

The setup is:
Working From HDFS Setup:

![image](https://cloud.githubusercontent.com/assets/8822075/7054638/b9497aba-de35-11e4-8772-e55a61205470.png)

Working Hostfile 

    127.0.0.1     sandbox.hortonworks.com

And the changes in the hive SQL from **event_date** to **earthquake_date**

**Comment by GISDev01** [comment]
Excellent!

**Comment by JamesMilnerUK** [comment]
Also feel free to use any of the screenshots in the documentation if they are useful. Might be good to have what the finished data should look like mapped :)

**Comment by climbage** [comment]
Awesome! We'll definitely want to work some of this into the documentation.

**Comment by GISDev01** [comment]
@JamesMilnerUK Just wondering, are you using VMWare Player or VirtualBox?

**Comment by JamesMilnerUK** [comment]
@GISDev01 I was using VirtualBox. I was following the [GIS Tools for Hadoop for Beginners](https://github.com/Esri/gis-tools-for-hadoop/wiki/GIS-Tools-for-Hadoop-for-Beginners)

**Comment by smambrose** [comment]
The above has been added to the documentation (the wikis). Thanks everyone!

**Comment by ymzzx** [comment]
I met the same problem as you@JamesMilnerUK, and I follow your step, but the same error,
Executing: CopyFromHDFS 192.168.152.113 50070 root /user/hive/warehouse/agg_samp d:\134.json
Start Time: Sat Aug 29 21:37:05 2015
Running script CopyFromHDFS...
Unexpected error : [Errno 11004] getaddrinfo failed
Traceback (most recent call last):
  File "<string>", line 277, in execute
  File "E:\hadoop_learning\geoprocessing-tools-for-hadoop-master\geoprocessing-tools-for-hadoop-master\webhdfs\webhdfs.py", line 152, in copyFromHDFS
    fileDownloadClient.request('GET', redirect_path, headers={})
  File "C:\Python27\ArcGIS10.2\Lib\httplib.py", line 958, in request
    self._send_request(method, url, body, headers)
  File "C:\Python27\ArcGIS10.2\Lib\httplib.py", line 992, in _send_request
    self.endheaders(body)
  File "C:\Python27\ArcGIS10.2\Lib\httplib.py", line 954, in endheaders
    self._send_output(message_body)
  File "C:\Python27\ArcGIS10.2\Lib\httplib.py", line 814, in _send_output
    self.send(msg)
  File "C:\Python27\ArcGIS10.2\Lib\httplib.py", line 776, in send
    self.connect()
  File "C:\Python27\ArcGIS10.2\Lib\httplib.py", line 757, in connect
    self.timeout, self.source_address)
  File "C:\Python27\ArcGIS10.2\Lib\socket.py", line 553, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
gaierror: [Errno 11004] getaddrinfo failed

could you help me ? Thanks a lot!

**Comment by ymzzx** [comment]
Please help me , @JamesMilnerUK  ,thanks a lot !

**Comment by ymzzx** [comment]
![qq 20150829220231](https://cloud.githubusercontent.com/assets/14030119/9562248/0c5c89e8-4e9a-11e5-9ff1-d81ccc6e66c2.png)
please help me , thanks a lot ! @mayur7789 @climbage  @randallwhitman  @GISDev01  @JamesMilnerUK

**Comment by climbage** [comment]
@ymzzx Can you get to the name node web UI through your browser?

**Comment by ymzzx** [comment]
Here is the details. I use vmware workstation ,there are three node in my vmware . of course ,one namenode ,two datanodes. I add the namenode and its IP in my host machine's host file (192.168.152.113  hadoop1), my host machine is win7. I can get to the namenode through http://192.168.152.113:50070 ,but I can not browse the filesystem in my hostmachine's browser.As the image shows,when I point the Browse the filesystem , there is error.
![22](https://cloud.githubusercontent.com/assets/14030119/9565517/1573e212-4f06-11e5-8bfc-71ba66686237.png)
![1111](https://cloud.githubusercontent.com/assets/14030119/9565518/159d9634-4f06-11e5-8d63-6a31e138c06d.png)

**Comment by ymzzx** [comment]
and another question, why the numRows is 0,as the image shows
![33](https://cloud.githubusercontent.com/assets/14030119/9565532/b0809ec6-4f06-11e5-9526-d1e0dc9f4b17.png) @climbage

**Comment by ymzzx** [comment]
maybe there are so many problems , thanks a lot ! @climbage

**Comment by amitabh74** [comment]
I am too facing the same problem. I am trying to copy from HDFS where HDFS server is on remote system. All the steps in turorial https://github.com/Esri/gis-tools-for-hadoop/wiki/Getting-the-results-of-a-Hive-query-into-ArcGIS has been followed as mentioned.
However running the "Copy from HDFS tool" shows following error:
Executing: CopyFromHDFS RHDCN05.rmsi.com 50070 hdfs /apps/hive/warehouse/taxi_agg E:\test.json
Start Time: Tue Jan 05 10:24:34 2016
Running script CopyFromHDFS...
Unexpected error : [Errno 10061] No connection could be made because the target machine actively refused it
Traceback (most recent call last):
  File "<string>", line 277, in execute
  File "E:\ESRI Hadoop Libraries\geoprocessing-tools-for-hadoop-master\webhdfs\webhdfs.py", line 152, in copyFromHDFS
    fileDownloadClient.request('GET', redirect_path, headers={})
  File "C:\Python27\ArcGIS10.3\Lib\httplib.py", line 995, in request
    self._send_request(method, url, body, headers)
  File "C:\Python27\ArcGIS10.3\Lib\httplib.py", line 1029, in _send_request
    self.endheaders(body)
  File "C:\Python27\ArcGIS10.3\Lib\httplib.py", line 991, in endheaders
    self._send_output(message_body)
  File "C:\Python27\ArcGIS10.3\Lib\httplib.py", line 844, in _send_output
    self.send(msg)
  File "C:\Python27\ArcGIS10.3\Lib\httplib.py", line 806, in send
    self.connect()
  File "C:\Python27\ArcGIS10.3\Lib\httplib.py", line 787, in connect
    self.timeout, self.source_address)
  File "C:\Python27\ArcGIS10.3\Lib\socket.py", line 571, in create_connection
    raise err
error: [Errno 10061] No connection could be made because the target machine actively refused it

Completed script CopyFromHDFS...
Failed to execute (CopyFromHDFS).
Failed at Tue Jan 05 10:24:37 2016 (Elapsed Time: 2.74 seconds)

**Comment by ymzzx** [comment]
OK，just copy your result as an usual way, without using the tools,you will find a nice end.------------------ Original ------------------

**Comment by amitabh74** [comment]
I did try what you are suggesting using following url:
rhdcn05.rmsi.com:50075/webhdfs/v1/apps/hive/warehouse/taxi_agg/000000_0?op=OPEN&namenoderpcaddress=RHDCN05.rmsi.com:8020&offset=0
and saving the output as json file and then opening it by converting it to feature class successfully.
However, the basic problem is not able to copy the table from HDFS.

**Comment by GISDev01** [comment]
@amitabh74 that is actually a different error than the original issue here. Please open a new issue, as this one can be closed. We want to avoid the common problem of github issues turning into forum threads. I can help you troubleshoot in a new issue.

**Comment by Cess-Zhu** [comment]
@ymzzx @amitabh74 I met the same problem just you did, but finally I figure out a solution. Hope that may help you.

First of all, the IP of my VM is **192.168.233.130**:
![hdp_2 3 2_vmare-2016-03-11-16-33-52](https://cloud.githubusercontent.com/assets/17264282/13697550/0f47b878-e7a9-11e5-97d0-996fd1cd35eb.png)

Change my OS host file to:
`192.168.233.130		sandbox.hortonworks.com`
![1](https://cloud.githubusercontent.com/assets/17264282/13697593/53278460-e7a9-11e5-9ea0-d1437d532bb7.png)

Then, fill the "HDFS host name" box with "sandbox.hortonworks.com" in "Copy From HDFS" tool:
![2](https://cloud.githubusercontent.com/assets/17264282/13697670/f55ae89e-e7a9-11e5-8009-7e38109f5c64.png)

and success:
![3](https://cloud.githubusercontent.com/assets/17264282/13698372/9409f2e2-e7ae-11e5-8e7f-b8dbc38fd0de.png)

This solution is pretty different, however it works. And I was inpired by @GISDev01 @JamesMilnerUK 
and @climbage . When I change
`http://sandbox.hortonworks.com:50075/webhdfs/v1/apps/hive/warehouse/taxi_agg/000000_0?op=OPEN&namenoderpcaddress=sandbox.hortonworks.com:8020&offset=0`
to
`http://192.168.233.130:50075/webhdfs/v1/apps/hive/warehouse/taxi_agg/000000_0?op=OPEN&namenoderpcaddress=sandbox.hortonworks.com:8020&offset=0`
I can get the json file.

But I am still wondering the reason why the error appears, and why I cannot use "localhost" as "HDFS server name" while my host file has already edited as `127.0.0.1		sandbox.hortonworks.com.` .

BTW, I'm using VMware and my physical machine's OS is Windows 10. And the VM shares the IP of the host.

**Comment by MjHow912** [comment]
Has anyone tried connecting to a Kerberized cluster from ArcMap to make this work? What was your workaround if so?

**Comment by wangbingzhang123** [comment]
@ymzzx  @amitabh74 @Cess-Zhu I met one of the same questions Error 10061 Have you solved it？Please help me.Thank you very much.

![1512380452 1](https://user-images.githubusercontent.com/34234140/33546698-a830ce1a-d91c-11e7-928c-b6c21ede9086.jpg)
