### ISSUE TITLE
Error creating UDF functions

### ISSUE THREAD

**Issue by pacorodrgz** [Esri/gis-tools-for-hadoop#26]
Hi all,

I'm very interested in carring uber tutorial out, as it would be quite useful for me in order to complete my university degree dissertation and hope you can help me. I tried every else sample but didn't succed performing them following that documentation step by step. This could be because Apache Hive doesn’t support geo spatial functions right out of the box.

I'm using Hortonworks HDP 2.1 sandbox as recommended in GIS-Tools-for-Hadoop documentation and already executed the following script to set up JAVA and install Maven:

rm /usr/bin/java
rm /usr/bin/javac
rm /usr/bin/javadoc
rm /usr/bin/javaws
ln -s /usr/java/jdk1.7.0_45/bin/java /usr/bin/java
ln -s /usr/java/jdk1.7.0_45/bin/javac /usr/bin/javac
ln -s /usr/java/jdk1.7.0_45/bin/javadoc /usr/bin/javadoc
ln -s /usr/java/jdk1.7.0_45/bin/javaws /usr/bin/javaws
echo "export JAVA_HOME=/usr/java/jdk1.7.0_45/" >> /etc/profile

wget http://mirror.symnds.com/software/Apache/maven/maven-3/3.1.1/binaries/apache-maven-3.1.1-bin.tar.gz
tar –zxvf apache-maven-3.1.1-bin.tar.gz
mv apache-maven-3.1.1 /usr/lib/maven
export PATH=$PATH:/usr/lib/maven/bin

After that, I built framework and api with Maven and added jar files into Hive. However, I got the error below at creating UDF functions ST_LineString, ST_Intersects and ST_Point:

hive> create temporary function ST_LineString as 'com.esri.hadoop.hive.ST_LineString';
java.lang.NoClassDefFoundError: com/esri/core/geometry/Geometry
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:270)
        at org.apache.hadoop.hive.ql.exec.FunctionTask.getUdfClass(FunctionTask.java:313)
        at org.apache.hadoop.hive.ql.exec.FunctionTask.createTemporaryFunction(FunctionTask.java:181)
        at org.apache.hadoop.hive.ql.exec.FunctionTask.execute(FunctionTask.java:81)
        at org.apache.hadoop.hive.ql.exec.Task.executeTask(Task.java:153)
        at org.apache.hadoop.hive.ql.exec.TaskRunner.runSequential(TaskRunner.java:85)
        at org.apache.hadoop.hive.ql.Driver.launchTask(Driver.java:1504)
        at org.apache.hadoop.hive.ql.Driver.execute(Driver.java:1271)
        at org.apache.hadoop.hive.ql.Driver.runInternal(Driver.java:1089)
        at org.apache.hadoop.hive.ql.Driver.run(Driver.java:912)
        at org.apache.hadoop.hive.ql.Driver.run(Driver.java:902)
        at org.apache.hadoop.hive.cli.CliDriver.processLocalCmd(CliDriver.java:268)
        at org.apache.hadoop.hive.cli.CliDriver.processCmd(CliDriver.java:220)
        at org.apache.hadoop.hive.cli.CliDriver.processLine(CliDriver.java:423)
        at org.apache.hadoop.hive.cli.CliDriver.executeDriver(CliDriver.java:793)
        at org.apache.hadoop.hive.cli.CliDriver.run(CliDriver.java:686)
        at org.apache.hadoop.hive.cli.CliDriver.main(CliDriver.java:625)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.apache.hadoop.util.RunJar.main(RunJar.java:212)
Caused by: java.lang.ClassNotFoundException: com.esri.core.geometry.Geometry
        at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
        ... 23 more
FAILED: Execution Error, return code -101 from org.apache.hadoop.hive.ql.exec.FunctionTask. com/esri/core/geometry/Geometry

I already checked ST_Point.java is within spatial-sdk-hive-1.1.1-SNAPSHOT.jar file and can't find out the reason of the error. May it be a jar version or a maven build issue?

Please, could you help me?

Thanks in advance.

**Comment by climbage** [comment]
It looks like you're missing the geometry api library.  Have you included that or just the jar with the hive functions?

**Comment by pacorodrgz** [comment]
Yes, I did add the following jar files by commands:
add jar hdfs:///user/esri/spatial-sdk-hive-1.1.1-SNAPSHOT.jar;
add jar hdfs:///user/esri/spatial-sdk-json-1.1.1-SNAPSHOT.jar;
add jar hdfs:///user/esri/esri-geometry-api-1.2.1.jar;

**Comment by climbage** [comment]
Interesting.  What happens if you add the geometry jar first, and then the others?

**Comment by pacorodrgz** [comment]
It works!! UDF function created! Thank you so much.

I need to execute any spatial query in order to take the resulting file into any visualization tool (Google Maps, Open Street Map, ArcGIS, etc.) and I'm trying to complete this Uber tutorial (http://ms-olap.blogspot.com.es/2015/02/geo-spatial-data-support-for-hive.html) as I wasn't able to carry any sample out by my own. However, Uber dataset from infochimps is not available. Do you know any step by step tested tutorial which I could use?

Thank you again.

**Comment by VickF** [comment]
Thanks much for this post.   Adding the jars in a different order made the difference for me also.

**Comment by matiji66** [comment]
oh another case to cause create  udf fail :https://issues.apache.org/jira/browse/HIVE-9410
