### ISSUE TITLE
ClassNotFoundException : Unable to find EnclosedEsriJsonInputFormat

### ISSUE THREAD

**Issue by oconnelc** [Esri/gis-tools-for-hadoop#73]
I've been following the instructions in the point-in-polygon-aggregation-hive tutorial. I've added all of the jars into Hive. When I run the following query: 

```
SELECT counties.name, count(*) cnt FROM counties
JOIN earthquakes
WHERE ST_Contains(counties.boundaryshape, ST_Point(earthquakes.longitude, earthquakes.latitude))
GROUP BY counties.name
ORDER BY cnt desc;
```
I get the following exception. 

```
Exceptioninthread"main"org.apache.hive.com.esotericsoftware.kryo.KryoException:Unabletofindclass:com.esri.json.hadoop.EnclosedEsriJsonInputFormat
Serializationtrace:
inputFileFormatClass(org.apache.hadoop.hive.ql.plan.TableDesc)
tblDesc(org.apache.hadoop.hive.ql.plan.FetchWork)
aliasToFetchWork(org.apache.hadoop.hive.ql.plan.MapredLocalWork)
	at org.apache.hive.com.esotericsoftware.kryo.util.DefaultClassResolver.readName(DefaultClassResolver.java:156)
	at org.apache.hive.com.esotericsoftware.kryo.util.DefaultClassResolver.readClass(DefaultClassResolver.java:133)
	at org.apache.hive.com.esotericsoftware.kryo.Kryo.readClass(Kryo.java:670)
	at org.apache.hadoop.hive.ql.exec.SerializationUtilities$KryoWithHooks.readClass(SerializationUtilities.java:181)
	at org.apache.hive.com.esotericsoftware.kryo.serializers.DefaultSerializers$ClassSerializer.read(DefaultSerializers.java:326)
	at org.apache.hive.com.esotericsoftware.kryo.serializers.DefaultSerializers$ClassSerializer.read(DefaultSerializers.java:314)
	at org.apache.hive.com.esotericsoftware.kryo.Kryo.readObjectOrNull(Kryo.java:759)
	at org.apache.hadoop.hive.ql.exec.SerializationUtilities$KryoWithHooks.readObjectOrNull(SerializationUtilities.java:199)
	at org.apache.hive.com.esotericsoftware.kryo.serializers.ObjectField.read(ObjectField.java:132)
	at org.apache.hive.com.esotericsoftware.kryo.serializers.FieldSerializer.read(FieldSerializer.java:551)
	at org.apache.hive.com.esotericsoftware.kryo.Kryo.readObject(Kryo.java:708)
	at org.apache.hadoop.hive.ql.exec.SerializationUtilities$KryoWithHooks.readObject(SerializationUtilities.java:214)
	at org.apache.hive.com.esotericsoftware.kryo.serializers.ObjectField.read(ObjectField.java:125)
	at org.apache.hive.com.esotericsoftware.kryo.serializers.FieldSerializer.read(FieldSerializer.java:551)
	at org.apache.hive.com.esotericsoftware.kryo.Kryo.readClassAndObject(Kryo.java:790)
	at org.apache.hadoop.hive.ql.exec.SerializationUtilities$KryoWithHooks.readClassAndObject(SerializationUtilities.java:176)
	at org.apache.hive.com.esotericsoftware.kryo.serializers.MapSerializer.read(MapSerializer.java:161)
	at org.apache.hive.com.esotericsoftware.kryo.serializers.MapSerializer.read(MapSerializer.java:39)
	at org.apache.hive.com.esotericsoftware.kryo.Kryo.readObject(Kryo.java:708)
	at org.apache.hadoop.hive.ql.exec.SerializationUtilities$KryoWithHooks.readObject(SerializationUtilities.java:214)
	at org.apache.hive.com.esotericsoftware.kryo.serializers.ObjectField.read(ObjectField.java:125)
	at org.apache.hive.com.esotericsoftware.kryo.serializers.FieldSerializer.read(FieldSerializer.java:551)
	at org.apache.hive.com.esotericsoftware.kryo.Kryo.readObject(Kryo.java:686)
	at org.apache.hadoop.hive.ql.exec.SerializationUtilities$KryoWithHooks.readObject(SerializationUtilities.java:206)
	at org.apache.hadoop.hive.ql.exec.SerializationUtilities.deserializeObjectByKryo(SerializationUtilities.java:607)
	at org.apache.hadoop.hive.ql.exec.SerializationUtilities.deserializePlan(SerializationUtilities.java:494)
	at org.apache.hadoop.hive.ql.exec.SerializationUtilities.deserializePlan(SerializationUtilities.java:478)
	at org.apache.hadoop.hive.ql.exec.SerializationUtilities.deserializePlan(SerializationUtilities.java:467)
	at org.apache.hadoop.hive.ql.exec.mr.ExecDriver.main(ExecDriver.java:762)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(NativeMethod)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.hadoop.util.RunJar.run(RunJar.java:239)
	at org.apache.hadoop.util.RunJar.main(RunJar.java:153)
Causedby:java.lang.ClassNotFoundException:com.esri.json.hadoop.EnclosedEsriJsonInputFormat
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(NativeMethod)
	at java.lang.Class.forName(Class.java:348)
	at org.apache.hive.com.esotericsoftware.kryo.util.DefaultClassResolver.readName(DefaultClassResolver.java:154)
```

I've verified that the EnclosedEsriJsonInputFormat resides in the spatial-sdk-json-2.0.0.jar. The exception appears to be thrown in a child JVM of the Hive-CLI. I suspect that some classpath is not set, but I've haven't had much luck. I've tried putting the jars in the HADOOP_CLASSPATH.

**Comment by randallwhitman** [comment]
Strange.  Do you happen to also have an older version of a Spatial Framework for Hadoop JAR file sitting somewhere?
What versions of Hive and Hadoop?

**Comment by oconnelc** [comment]
Hadoop version:  2.9.0 
Hive version: 2.3.2

Where would the spatial framework for Hadoop most likely be located? 

I was able to get it to work once I added the jars to the $HADOOP_CLASSPATH

**Comment by randallwhitman** [comment]
Great to hear to you got it to work.
I wonder if something like [HIVE-6670](https://issues.apache.org/jira/browse/HIVE-6670) resurfaced with recent versions of Hive - cross-reference #9.
