### ISSUE TITLE
Exception after running the Hive QL 

### ISSUE THREAD

**Issue by sudeepdestiny** [Esri/gis-tools-for-hadoop#74]
hive> set hive.auto.convert.join=false;
hive> SELECT counties.name, count(*) cnt FROM counties
    > JOIN earthquakes
    > WHERE ST_Contains(counties.boundaryshape, ST_Point(earthquakes.longitude, earthquakes.latitude))
    > GROUP BY counties.name
    > ORDER BY cnt desc;
Warning: Shuffle Join JOIN[4][tables = [counties, earthquakes]] in Stage 'Stage-1:MAPRED' is a cross product
Query ID = cloudera_20180418234444_b0fe6072-007c-468a-a4fc-9a0477c09074
Total jobs = 3
Launching Job 1 out of 3
Number of reduce tasks determined at compile time: 1
In order to change the average load for a reducer (in bytes):
  set hive.exec.reducers.bytes.per.reducer=<number>
In order to limit the maximum number of reducers:
  set hive.exec.reducers.max=<number>
In order to set a constant number of reducers:
  set mapreduce.job.reduces=<number>
Starting Job = job_1523762198252_0006, Tracking URL = http://quickstart.cloudera:8088/proxy/application_1523762198252_0006/
Kill Command = /usr/lib/hadoop/bin/hadoop job  -kill job_1523762198252_0006
Hadoop job information for Stage-1: number of mappers: 2; number of reducers: 1
2018-04-18 23:45:18,594 Stage-1 map = 0%,  reduce = 0%
2018-04-18 23:46:10,583 Stage-1 map = 50%,  reduce = 0%, Cumulative CPU 3.23 sec
2018-04-18 23:47:11,510 Stage-1 map = 50%,  reduce = 0%, Cumulative CPU 3.23 sec
2018-04-18 23:47:16,178 Stage-1 map = 100%,  reduce = 100%, Cumulative CPU 3.23 sec
MapReduce Total cumulative CPU time: 3 seconds 230 msec
Ended Job = job_1523762198252_0006 with errors
Error during job, obtaining debugging information...
Job Tracking URL: http://quickstart.cloudera:8088/proxy/application_1523762198252_0006/
Examining task ID: task_1523762198252_0006_m_000000 (and more) from job job_1523762198252_0006

Task with the most failures(4): 
-----
Task ID:
  task_1523762198252_0006_m_000000

URL:
  http://0.0.0.0:8088/taskdetails.jsp?jobid=job_1523762198252_0006&tipid=task_1523762198252_0006_m_000000
-----
Diagnostic Messages for this Task:
**Error: java.io.IOException: java.io.IOException: com.fasterxml.jackson.core.JsonParseException: Unexpected character ('<' (code 60)): expected a valid value (number, String, array, object, 'true', 'false' or 'null')**
 at [Source: org.apache.hadoop.hdfs.client.HdfsDataInputStream@71d674e2: org.apache.hadoop.hdfs.DFSInputStream@3693dbd1; line: 7, column: 2]
	at org.apache.hadoop.hive.io.HiveIOExceptionHandlerChain.handleRecordReaderNextException(HiveIOExceptionHandlerChain.java:121)
	at org.apache.hadoop.hive.io.HiveIOExceptionHandlerUtil.handleRecordReaderNextException(HiveIOExceptionHandlerUtil.java:77)
	at org.apache.hadoop.hive.shims.HadoopShimsSecure$CombineFileRecordReader.doNextWithExceptionHandler(HadoopShimsSecure.java:227)
	at org.apache.hadoop.hive.shims.HadoopShimsSecure$CombineFileRecordReader.next(HadoopShimsSecure.java:137)
	at org.apache.hadoop.mapred.MapTask$TrackedRecordReader.moveToNext(MapTask.java:199)
	at org.apache.hadoop.mapred.MapTask$TrackedRecordReader.next(MapTask.java:185)
	at org.apache.hadoop.mapred.MapRunner.run(MapRunner.java:52)
	at org.apache.hadoop.mapred.MapTask.runOldMapper(MapTask.java:459)
	at org.apache.hadoop.mapred.MapTask.run(MapTask.java:343)
	at org.apache.hadoop.mapred.YarnChild$2.run(YarnChild.java:164)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:415)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1917)
	at org.apache.hadoop.mapred.YarnChild.main(YarnChild.java:158)
Caused by: java.io.IOException: com.fasterxml.jackson.core.JsonParseException: Unexpected character ('<' (code 60)): expected a valid value (number, String, array, object, 'true', 'false' or 'null')
 at [Source: org.apache.hadoop.hdfs.client.HdfsDataInputStream@71d674e2: org.apache.hadoop.hdfs.DFSInputStream@3693dbd1; line: 7, column: 2]
	at org.apache.hadoop.hive.io.HiveIOExceptionHandlerChain.handleRecordReaderNextException(HiveIOExceptionHandlerChain.java:121)
	at org.apache.hadoop.hive.io.HiveIOExceptionHandlerUtil.handleRecordReaderNextException(HiveIOExceptionHandlerUtil.java:77)
	at org.apache.hadoop.hive.ql.io.HiveContextAwareRecordReader.doNext(HiveContextAwareRecordReader.java:365)
	at org.apache.hadoop.hive.ql.io.CombineHiveRecordReader.doNext(CombineHiveRecordReader.java:116)
	at org.apache.hadoop.hive.ql.io.CombineHiveRecordReader.doNext(CombineHiveRecordReader.java:43)
	at org.apache.hadoop.hive.ql.io.HiveContextAwareRecordReader.next(HiveContextAwareRecordReader.java:116)
	at org.apache.hadoop.hive.shims.HadoopShimsSecure$CombineFileRecordReader.doNextWithExceptionHandler(HadoopShimsSecure.java:225)
	... 11 more
Caused by: com.fasterxml.jackson.core.JsonParseException: Unexpected character ('<' (code 60)): expected a valid value (number, String, array, object, 'true', 'false' or 'null')
 at [Source: org.apache.hadoop.hdfs.client.HdfsDataInputStream@71d674e2: org.apache.hadoop.hdfs.DFSInputStream@3693dbd1; line: 7, column: 2]
	at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1369)
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:532)
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportUnexpectedChar(ParserMinimalBase.java:453)
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._handleUnexpectedValue(UTF8StreamJsonParser.java:2278)
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._nextTokenNotInObject(UTF8StreamJsonParser.java:779)
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser.nextToken(UTF8StreamJsonParser.java:665)
	at com.esri.json.hadoop.EnclosedBaseJsonRecordReader.next(EnclosedBaseJsonRecordReader.java:111)
	at com.esri.json.hadoop.EnclosedBaseJsonRecordReader.next(EnclosedBaseJsonRecordReader.java:27)
	at org.apache.hadoop.hive.ql.io.HiveContextAwareRecordReader.doNext(HiveContextAwareRecordReader.java:360)
	... 15 more

FAILED: Execution Error, return code 2 from org.apache.hadoop.hive.ql.exec.mr.MapRedTask
MapReduce Jobs Launched: 
Stage-Stage-1: Map: 2  Reduce: 1   Cumulative CPU: 3.23 sec   HDFS Read: 46636 HDFS Write: 0 FAIL
Total MapReduce CPU Time Spent: 3 seconds 230 msec

**Comment by randallwhitman** [comment]
Was that using the counties and earthquakes data from this repository?
What versions of Hive and Hadoop?
What happens without any custom Hive setting?

**Comment by anujvidooly** [comment]
FAILED: Execution Error, return code 2 from org.apache.hadoop.hive.ql.exec.mr.MapRedTask
MapReduce Jobs Launched: 
Stage-Stage-1: Map: 1  Reduce: 1   HDFS Read: 0 HDFS Write: 0 FAIL
Total MapReduce CPU Time Spent: 0 msec
hive>
