### ISSUE TITLE
Unable to create counties table from tutorial

### ISSUE THREAD

**Issue by CeSul** [Esri/gis-tools-for-hadoop#75]
Hi,

I'm following along with [Aggregation Sample for Hive](https://github.com/Esri/gis-tools-for-hadoop/tree/master/samples/point-in-polygon-aggregation-hive)  and am having trouble at this stage:

`
CREATE TABLE counties (Area string, Perimeter string, State string, County string, Name string, BoundaryShape binary)
ROW FORMAT SERDE 'com.esri.hadoop.hive.serde.EsriJsonSerDe'
STORED AS INPUTFORMAT 'com.esri.json.hadoop.EnclosedEsriJsonInputFormat'
OUTPUTFORMAT 'org.apache.hadoop.hive.ql.io.HiveIgnoreKeyTextOutputFormat'
LOCATION '/staging/ess/csul/playground/';
`

I get this result instead
`
FAILED: Execution Error, return code 1 from org.apache.hadoop.hive.ql.exec.DDLTask. com/fasterxml/jackson/core/JsonParseException
`
I've noticed that when I omit `ROW FORMAT SERDE 'com.esri.hadoop.hive.serde.EsriJsonSerDe'` (seems important but I thought I'd just try it) Hive returns 'OK' but the demo analysis fails.

Any advice would be appreciated. Thanks!

**Comment by carloseduardotoledo** [comment]
Hi Cesar,



Have you tried not to use the LOCATION statement, and let Hive create the
table on a maneged structure without data, and after that LOAD the data?



The SerDe is supposed to Deserialize the row to an object of the type
defined in INPUTFORMAT and Serialize the row to an object of the type
defined in OUTPUTFORMAT.



If ‘/staging/ess/csul/playground/’ already has data not formatted as
INPUTFORMAT, it will probably raises an exception.



Best regards,

**Comment by CeSul** [comment]
Hi,

Thanks for your responses. I added the LOCATION statement because running this command:

```
CREATE TABLE earthquakes (earthquake_date STRING, latitude DOUBLE, longitude DOUBLE, depth DOUBLE, magnitude DOUBLE,
    magtype string, mbstations string, gap string, distance string, rms string, source string, eventid string)
ROW FORMAT DELIMITED FIELDS TERMINATED BY ','
STORED AS TEXTFILE;

```
Gives me this error
`FAILED: Execution Error, return code 1 from org.apache.hadoop.hive.ql.exec.DDLTask. MetaException(message:file:/user/hive/warehouse/earthquakes is not a directory or unable to create one)`

I'm on a shared system and only have write permissions to specific directories so I thought would redirect what ever is supposed to happen to ‘/staging/ess/csul/playground/’.

I'll double check to make sure that I can load in simple data before the more complicated county data. 

Best,
Cesar

**Comment by Data-drone** [comment]
I also can't create the table either.

I get:

`Name: java.lang.ClassNotFoundException
Message: com.esri.json.hadoop.EnclosedEsriJsonInputFormat
StackTrace:   at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
  at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
  at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
  at java.lang.Class.forName0(Native Method)
  at java.lang.Class.forName(Class.java:348)
  at org.apache.spark.util.Utils$.classForName(Utils.scala:242)
  at org.apache.spark.sql.hive.client.HiveClientImpl$.org$apache$spark$sql$hive$client$HiveClientImpl$$toInputFormat(HiveClientImpl.scala:917)
  at org.apache.spark.sql.hive.client.HiveClientImpl$$anonfun$toHiveTable$4.apply(HiveClientImpl.scala:953)
  at org.apache.spark.sql.hive.client.HiveClientImpl$$anonfun$toHiveTable$4.apply(HiveClientImpl.scala:953)
  at scala.Option.map(Option.scala:146)
  at org.apache.spark.sql.hive.client.HiveClientImpl$.toHiveTable(HiveClientImpl.scala:953)
  at org.apache.spark.sql.hive.client.HiveClientImpl$$anonfun$createTable$1.apply$mcV$sp(HiveClientImpl.scala:489)
  at org.apache.spark.sql.hive.client.HiveClientImpl$$anonfun$createTable$1.apply(HiveClientImpl.scala:487)
  at org.apache.spark.sql.hive.client.HiveClientImpl$$anonfun$createTable$1.apply(HiveClientImpl.scala:487)
  at org.apache.spark.sql.hive.client.HiveClientImpl$$anonfun$withHiveState$1.apply(HiveClientImpl.scala:283)
  at org.apache.spark.sql.hive.client.HiveClientImpl.liftedTree1$1(HiveClientImpl.scala:221)
  at org.apache.spark.sql.hive.client.HiveClientImpl.retryLocked(HiveClientImpl.scala:220)
  at org.apache.spark.sql.hive.client.HiveClientImpl.withHiveState(HiveClientImpl.scala:266)
  at org.apache.spark.sql.hive.client.HiveClientImpl.createTable(HiveClientImpl.scala:487)
  at org.apache.spark.sql.hive.HiveExternalCatalog$$anonfun$createTable$1.apply$mcV$sp(HiveExternalCatalog.scala:299)
  at org.apache.spark.sql.hive.HiveExternalCatalog$$anonfun$createTable$1.apply(HiveExternalCatalog.scala:238)
  at org.apache.spark.sql.hive.HiveExternalCatalog$$anonfun$createTable$1.apply(HiveExternalCatalog.scala:238)
  at org.apache.spark.sql.hive.HiveExternalCatalog.withClient(HiveExternalCatalog.scala:99)
  at org.apache.spark.sql.hive.HiveExternalCatalog.createTable(HiveExternalCatalog.scala:238)
  at org.apache.spark.sql.catalyst.catalog.ExternalCatalogWithListener.createTable(ExternalCatalogWithListener.scala:102)
  at org.apache.spark.sql.catalyst.catalog.SessionCatalog.createTable(SessionCatalog.scala:319)
  at org.apache.spark.sql.execution.command.CreateTableCommand.run(tables.scala:128)
  at org.apache.spark.sql.execution.command.ExecutedCommandExec.sideEffectResult$lzycompute(commands.scala:70)
  at org.apache.spark.sql.execution.command.ExecutedCommandExec.sideEffectResult(commands.scala:68)
  at org.apache.spark.sql.execution.command.ExecutedCommandExec.executeCollect(commands.scala:79)
  at org.apache.spark.sql.Dataset$$anonfun$6.apply(Dataset.scala:194)
  at org.apache.spark.sql.Dataset$$anonfun$6.apply(Dataset.scala:194)
  at org.apache.spark.sql.Dataset$$anonfun$53.apply(Dataset.scala:3364)
  at org.apache.spark.sql.execution.SQLExecution$$anonfun$withNewExecutionId$1.apply(SQLExecution.scala:78)
  at org.apache.spark.sql.execution.SQLExecution$.withSQLConfPropagated(SQLExecution.scala:125)
  at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:73)
  at org.apache.spark.sql.Dataset.withAction(Dataset.scala:3363)
  at org.apache.spark.sql.Dataset.<init>(Dataset.scala:194)
  at org.apache.spark.sql.Dataset$.ofRows(Dataset.scala:79)
  at org.apache.spark.sql.SparkSession.sql(SparkSession.scala:651)`

I am running in Spark scala and have used:

`sc.addJar("gis-tools-for-hadoop/samples/lib/esri-geometry-api-2.0.0.jar")
sc.addJar("gis-tools-for-hadoop/samples/lib/spatial-sdk-hive-2.0.0.jar")
sc.addJar("gis-tools-for-hadoop/samples/lib/spatial-sdk-json-2.0.0.jar")`

to get the code to work.

All the other statements up to that point have worked. I tried also adding those jars to my `HADOOP_CLASSPATH` should HADOOP_CLASSPATH point to local folders on the gateway instances I am running the code from or from HDFS? 

any ideas?

**Comment by randallwhitman** [comment]
`sc.addJar` should work, though I routinely use `--jars` and `--driver-class-path` on the command-line for `spark-sql` and `spark-submit`.
